### ISSUE TITLE
There is a little BUG

### ISSUE THREAD

**Issue by zjkal** [stestagg/dateformat#3]
**Code:**
`from dateformat import DateFormat`

`date_format = DateFormat("DD.mm.YYYY")`
`print(int(date_format.parse('31.10.2022').timestamp()))`

**Error:**
`Traceback (most recent call last):`
`  File "scratch.py", line 4, in <module>`
`    print(int(date_format.parse('31.10.2022').timestamp()))`
`  File "dateformat.py", line 501, in parse`
`    result = datetime.datetime(**context)`
`ValueError: day is out of range for month`

**Comment by stestagg** [comment]
Hi, Thanks for the report. 

I think you should try:

```
date_format = DateFormat("DD.MM.YYYY")
```

(with MM rather than mm),

In the dateformat library, 'mm' means minute, whereas 'MM' is month (I know this is different from some other libraries, but the idea is that the date parts are generally capital, and the time parts are generally lower-case.

This should work for you:
```
>>> import dateformat
>>> date_format = dateformat.DateFormat("DD.MM.YYYY")
>>> date_format.parse('31.10.2022')
datetime.datetime(2022, 10, 31, 0, 0)
```

**Comment by zjkal** [comment]
Yes, It woks well. Thank you very much again!~
